/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Cursor;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author C. Levallois
 */
public class Screen2 extends javax.swing.JFrame {

    public static String fileSelectedPathANdName = "nothing";

    /**
     * Creates new form Screen2
     */
    public Screen2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        closeParameters = new javax.swing.JButton();
        binaryBox = new javax.swing.JCheckBox();
        nGramsField = new javax.swing.JTextField();
        minCharsField = new javax.swing.JTextField();
        maxWordsField = new javax.swing.JTextField();
        nGrams = new javax.swing.JLabel();
        numChars = new javax.swing.JLabel();
        maxWords = new javax.swing.JLabel();
        binaryCounting = new javax.swing.JLabel();
        openStopWordsFile = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        minOccurrences = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        deleteChars = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText(org.openide.util.NbBundle.getMessage(Screen2.class, "Screen2.jLabel1.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(Screen2.class, "Screen2.jLabel2.text")); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel2MouseMoved(evt);
            }
        });

        closeParameters.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        closeParameters.setText(org.openide.util.NbBundle.getMessage(Screen2.class, "Screen2.closeParameters.text")); // NOI18N
        closeParameters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeParametersActionPerformed(evt);
            }
        });

        binaryBox.setBackground(new java.awt.Color(255, 255, 255));
        binaryBox.setSelected(true);
        binaryBox.setText(org.openide.util.NbBundle.getMessage(Screen2.class, "Screen2.binaryBox.text")); // NOI18N

        nGramsField.setText(org.openide.util.NbBundle.getMessage(Screen2.class, "Screen2.nGramsField.text")); // NOI18N

        minCharsField.setText(org.openide.util.NbBundle.getMessage(Screen2.class, "Screen2.minCharsField.text")); // NOI18N
        minCharsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minCharsFieldActionPerformed(evt);
            }
        });

        maxWordsField.setText(org.openide.util.NbBundle.getMessage(Screen2.class, "Screen2.maxWordsField.text")); // NOI18N
        maxWordsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxWordsFieldActionPerformed(evt);
            }
        });

        nGrams.setText(org.openide.util.NbBundle.getMessage(Screen2.class, "Screen2.nGrams.text")); // NOI18N

        numChars.setText(org.openide.util.NbBundle.getMessage(Screen2.class, "Screen2.numChars.text")); // NOI18N

        maxWords.setText(org.openide.util.NbBundle.getMessage(Screen2.class, "Screen2.maxWords.text")); // NOI18N

        binaryCounting.setLabelFor(binaryBox);
        binaryCounting.setText(org.openide.util.NbBundle.getMessage(Screen2.class, "Screen2.binaryCounting.text")); // NOI18N

        openStopWordsFile.setText(org.openide.util.NbBundle.getMessage(Screen2.class, "Screen2.openStopWordsFile.text")); // NOI18N
        openStopWordsFile.setToolTipText(org.openide.util.NbBundle.getMessage(Screen2.class, "Screen2.openStopWordsFile.toolTipText")); // NOI18N
        openStopWordsFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openStopWordsFileActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel7.setText(org.openide.util.NbBundle.getMessage(Screen2.class, "Screen2.jLabel7.text")); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText(org.openide.util.NbBundle.getMessage(Screen2.class, "Screen2.jLabel3.text")); // NOI18N

        minOccurrences.setText(org.openide.util.NbBundle.getMessage(Screen2.class, "Screen2.minOccurrences.text")); // NOI18N

        jLabel4.setText(org.openide.util.NbBundle.getMessage(Screen2.class, "Screen2.jLabel4.text")); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel5.setText(org.openide.util.NbBundle.getMessage(Screen2.class, "Screen2.jLabel5.text")); // NOI18N

        jLabel6.setText(org.openide.util.NbBundle.getMessage(Screen2.class, "Screen2.jLabel6.text")); // NOI18N

        jLabel8.setText(org.openide.util.NbBundle.getMessage(Screen2.class, "Screen2.jLabel8.text")); // NOI18N

        deleteChars.setBackground(new java.awt.Color(255, 255, 255));
        deleteChars.setSelected(true);
        deleteChars.setText(org.openide.util.NbBundle.getMessage(Screen2.class, "Screen2.deleteChars.text")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nGrams)
                            .addComponent(openStopWordsFile)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel7))
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(numChars)
                                    .addComponent(maxWords)
                                    .addComponent(binaryCounting)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(deleteChars)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(nGramsField)
                                        .addComponent(minCharsField)
                                        .addComponent(binaryBox)
                                        .addComponent(maxWordsField)
                                        .addComponent(minOccurrences))))
                            .addComponent(closeParameters)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(deleteChars))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(binaryBox)
                    .addComponent(binaryCounting))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nGrams)
                    .addComponent(nGramsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numChars)
                    .addComponent(minCharsField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxWordsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxWords))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(minOccurrences, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(38, 38, 38)
                .addComponent(openStopWordsFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(33, 33, 33)
                .addComponent(closeParameters)
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeParametersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeParametersActionPerformed
        Screen1.screen1.setVisible(true);
        Screen1.screen2.setVisible(false);
    }//GEN-LAST:event_closeParametersActionPerformed

    private void minCharsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minCharsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minCharsFieldActionPerformed

    private void maxWordsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxWordsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maxWordsFieldActionPerformed

    private void openStopWordsFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openStopWordsFileActionPerformed
        if (evt.getSource() == openStopWordsFile) {
            System.out.println("openStopWordsFile clicked");


        }
        JFileChooser chooser = new JFileChooser();
        //chooser.setCurrentDirectory(new java.io.File("D:\\Docs Pro Clement\\E-humanities\\TextMining\\Exported Items\\"));
        chooser.setDialogTitle("Select a file with stopwords (comma separated)");
        //chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);
        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            fileSelectedPathANdName = chooser.getSelectedFile().toString();
            System.out.println("Selected File for Stopwords: " + fileSelectedPathANdName);
        } else {
            System.out.println("No Selection");
        }
    }//GEN-LAST:event_openStopWordsFileActionPerformed

    private void jLabel2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseMoved
        jLabel2.setCursor(new Cursor(Cursor.HAND_CURSOR));

    }//GEN-LAST:event_jLabel2MouseMoved

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        try {
            try {
                Desktop.getDesktop().browse(new java.net.URI("http://www.vosviewer.com"));
            } catch (URISyntaxException ex) {
                Logger.getLogger(Screen2.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (IOException ex) {
            Logger.getLogger(Screen2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel2MouseClicked
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JCheckBox binaryBox;
    private javax.swing.JLabel binaryCounting;
    private javax.swing.JButton closeParameters;
    public static javax.swing.JCheckBox deleteChars;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel maxWords;
    public static javax.swing.JTextField maxWordsField;
    public static javax.swing.JTextField minCharsField;
    public static javax.swing.JTextField minOccurrences;
    private javax.swing.JLabel nGrams;
    public static javax.swing.JTextField nGramsField;
    private javax.swing.JLabel numChars;
    private javax.swing.JButton openStopWordsFile;
    // End of variables declaration//GEN-END:variables
}
