/* Generated By:JavaCC: Do not edit this line. TokenSequenceParserConstants.java */
package edu.stanford.nlp.ling.tokensregex;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
interface TokenSequenceParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IDENTIFIER = 4;
  /** RegularExpression Id. */
  int VAR = 5;
  /** RegularExpression Id. */
  int BACKREF = 6;
  /** RegularExpression Id. */
  int INT = 7;
  /** RegularExpression Id. */
  int REAL = 8;
  /** RegularExpression Id. */
  int REGEX = 9;
  /** RegularExpression Id. */
  int STR = 10;
  /** RegularExpression Id. */
  int BARESTR = 11;
  /** RegularExpression Id. */
  int NUMCMP = 12;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "<IDENTIFIER>",
    "<VAR>",
    "<BACKREF>",
    "<INT>",
    "<REAL>",
    "<REGEX>",
    "<STR>",
    "<BARESTR>",
    "<NUMCMP>",
    "\"*\"",
    "\"?\"",
    "\"+\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\"|\"",
    "\"&\"",
    "\"(\"",
    "\"?:\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"!\"",
    "\";\"",
    "\":\"",
    "\"#\"",
    "\"(?m)\"",
    "\"=>\"",
    "\"&annotate\"",
    "\"=\"",
  };

}
